name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install --frozen-lockfile

      - name: clone ghost-chat
        run: cd .. && git clone https://github.com/Enubia/ghost-chat.git

      - name: install ghost-chat dependencies
        run: cd ../ghost-chat && npm install

      - name: link slurp-config
        run: npm link --dir ../ghost-chat

      - name: lint
        run: 
          cd ../ghost-chat &&
          npm run lint:src &&
          npm run lint:shared &&
          npm run lint:electron