name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: clone ghost-chat
        run: cd .. && git clone https://github.com/Enubia/ghost-chat.git

      - name: install ghost-chat dependencies
        run: cd ../ghost-chat && pnpm install

      - name: link slurp-config
        run: pnpm link --dir ../ghost-chat

      - name: lint
        run: 
          cd ../ghost-chat &&
          pnpm exec eslint --ext .ts --ignore-path .eslintignore src/ &&
          pnpm exec eslint --ext .ts --ignore-path .eslintignore shared/ &&
          pnpm exec eslint --ext .ts --ignore-path .eslintignore electron/